### ISSUE TITLE
Find key themes from Industry interview results

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#101]
This ticket documents research analysis activities for Industry interview results.

**Acceptance Criteria:**
- [x] Upload notes to Miro
- [x] Pull out problems/opportunities (data) from each note document
- [x] Compile data from all interviews (colour-coded to identify participant)
- [x] Sort data into key themes

**Comment by LindsayMacfarlane** [comment]
So fascinating to see this all come together and see the patterns/themes that are emerging. Well done @jaimiebutton !
