### ISSUE TITLE
Find key themes from Academia interview results

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#102]
This ticket documents research analysis activities for Academia interview results.

**Acceptance Criteria:**
- [x] Upload notes to Miro
- [x] Pull out problems/opportunities (data) from each note document
- [x] Compile data from all interviews (colour-coded to identify participant)
- [x] Sort data into key themes

**Comment by LindsayMacfarlane** [comment]
Interesting to see there are less theme's coming out of the academic research notes, but no less impactful. Well done @jaimiebutton !
