### ISSUE TITLE
Conduct interviews with industry

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#105]
It's time to conduct interviews with industry operators! This card can stay in progress until this sprint's interviews are completed.

**Acceptance criteria:**
- [x] Obtain User Engagement Consent Form 
- [x] Conduct interviews

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton. This was fascinating and so insightful to learn how industry is using/not using the data and information.
