### ISSUE TITLE
Write questions for ESG companies

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#108]
ESG reporting companies have a lot of insight they can share with us about how industry currently reports and how that will change in the near future. After ticket #95, we will need an interview guide for the conversations.

**Acceptance Criteria:**
- [x] Create new folder in Teams channel
- [x] Create a template document
- [x] Write out goals of interview
- [x] Create questions

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! Super excited for these interviews :)
