### ISSUE TITLE
Find key themes from ESG Company interview results

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#109]
This ticket documents research analysis activities for ESG Company interview results.

**Acceptance Criteria:**
- [x] Upload notes to Miro
- [x] Pull out problems/opportunities (data) from each note document
- [x] Compile data from all interviews (colour-coded to identify participant)
- [x] Sort data into key themes

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
