### ISSUE TITLE
Create final report

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#111]
this card: 
- second draft created
- send draft to Lindsay & Diana for feedback
 - send draft to Chris and Emilie for feedback

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - pulling this into in progress...I feel you mentioned at standup that you were working on it ;)

**Comment by Dianadec** [comment]
Jaimie to split this into the cards as above.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - let me know once this ticket has been split and I can close.

**Comment by LindsayMacfarlane** [comment]
Thank you for all your work on this @jaimiebutton!
