### ISSUE TITLE
Schedule Industry & Academia research analysis session with ES

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#112]
Research analysis is best done with more than one set of eyes! This ticket documents analyzing results from Industry & Academia interviews to find common themes, key user personas, and possibly problem statements.

**Acceptance Criteria:**
- [x] Identify the goals of session
- [x] Schedule time with ES

**Comment by LindsayMacfarlane** [comment]
Remind me what the difference is between this one and recommendation session? I know we discussed this. Is this more around analyzing the feedback to-date? Do you want to add holding the session as well?

**Comment by jaimiebutton** [comment]
Session scheduled for Sep. 14

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton !
