### ISSUE TITLE
Research analysis for BC Gov Part 2

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#113]
Oh, research analysis! An important time in the life of any research project. A few sprints ago, we spent some time [analyzing patterns in BC Gov interview results](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/78). Now that we've finished off the BC Gov phase, let's go back and add information from interviews we've held since.

**Acceptance Criteria:**
 - [x] Review note-taking docs for each conversation
 - [x] Document patterns and themes in Miro
 - [x] Share findings with project team

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I look forward to reviewing and seeing the results :)
