### ISSUE TITLE
Create report outline

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#118]
The goal of this ticket is to have a structure for the report that identifies the types of sections that will be expanded on in the future.

Acceptance Criteria:

- [x] Identify segments of report
- [x] Get feedback on segments from project team
- [x] Write high-level bullets for segments

**Comment by LindsayMacfarlane** [comment]
It's coming together! I'm so excited for this part :) Way to go @jaimiebutton!
