### ISSUE TITLE
Refine BC Gov Problem Statements

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#120]
A few sprints ago, we created [hypothesis problem statements ](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/88)for core BC gov users. Now that we've learned a bit more, let's go back and refine the statements we had!

**Acceptance Criteria:**
- [x] Review existing statements
- [x] Address comments left
- [x] Add missing personas if needed
- [x] Refine statements
- [x] Share with project team

**Comment by LindsayMacfarlane** [comment]
Thank you so much @jaimiebutton! This has been a lot of great work.
