### ISSUE TITLE
Put interview recordings in PR channel

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#125]
With many interviews comes many video recordings. Let's make sure we're keeping them all in one place.

**Upload the following interviews to the Public Reporting (Private) Teams channel:**
- [x] ESG Centre of Excellence - Aug 15
- [x] Cumulative Effects - Aug 15
- [x] SFU - Aug 19
- [x] Forestry - Aug 19

**Comment by LindsayMacfarlane** [comment]
Also make sure any signed consent forms also get saved with the interviews.

**Comment by jaimiebutton** [comment]
SFU was the only external one and those are good to go - but a helpful note as we go along :)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton for making sure all our documentation is centrally stored and accessible!
