### ISSUE TITLE
Re-spark Conversation on Indigenous Engagement Opportunities

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#126]
After connecting with the CleanBC team, it was identified as an objective to reconnect with Katie M-S to identify potential opportunities for engagement with indigenous organizations and tables over the fall.

_Acceptance criteria:_
- [x] Reach out to Katie

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton ! Based on the feedback, this seems like it will end up being a bit of a gap in our research. That's ok. We can reference the report(s) Katie provided around Indigenous data needs and make recommendations that Indigenous communities should be engaged for input during later stages of the project.
