### ISSUE TITLE
Schedule recommendation session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#127]
One main aim of this project is to provide future recommendations based on learnings accumulated from our research. 

**Acceptance criteria:**
- [x] Schedule recommendation session
- [x] Write calendar invite description

_Note: Schedule for near the end of Sprint 10 (Sep 5-16)_

**Comment by LindsayMacfarlane** [comment]
Do you need a ticket to hold the session or will that be captured as part of this ticket?

**Comment by jaimiebutton** [comment]
Good call, I'll create one

**Comment by jaimiebutton** [comment]
Scheduled for Sep. 16

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton !
