### ISSUE TITLE
Refine Project Charter

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#13]
A [project charter](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Project%20Charter/DRAFT_Public%20Report%20Project%20Charter.docx?d=wf71ac22670974aabbc4ba75271f5626e&csf=1&web=1) was created to set expectations for the upcoming project. This ticket documents some work to update the charter.

**Description:**
- [x] Update project outcomes to include: "Analysis of problem and leverage points in system"
- [x] Update teammate capacity (currently says TBD)
- [x] include signature spot for Director
- [x] Once finalized review with ED and other signatories for signatures

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, here are the changes I'm proposing to the charter. Any feedback on the above?

**Comment by LindsayMacfarlane** [comment]
I have slight reservations about adding press as stakeholders. There's probably no issue in identifying, but we will have to discuss if and how discovery can include them.
