### ISSUE TITLE
Add resources from SFU Call to project documentation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#130]
Our call with Thomas and Bradford from SFU was very insightful to the team. We were also directed to a number of people in academia and beyond for follow-up conversations.

**Acceptance Criteria:**
- [x] Go through interview notes for recommended people
- [x] Go through Thomas' follow-up email
- [x] Add contacts to Contact Tracker

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton !
