### ISSUE TITLE
Problem Statements for Industry

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#133]
Following ticket #101, let's generate problem statements for Industry. The creation of a hypothesis Problem Statement will help us summarize in our findings in a way that easily be shared, iterated on, and most of all... gives us a problem to work towards in future work.

Acceptance criteria:
- [x] Create frame in Miro for Industry problem statements
- [x] Create hypothesis problem statements from research findings
- [x] Share problem statements with project team

**Comment by LindsayMacfarlane** [comment]
Thank you so much @jaimiebutton!
