### ISSUE TITLE
Make the report look goooooood

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#153]
Alright, it's time. Let's make 'er look goooooood.

Acceptance Criteria:
- [x] Create executive summary
- [x] Create cover page
- [x] Define report design style
- [x] Format report in design style

**Comment by Dianadec** [comment]
@jaimiebutton can I help come up with some AC for this card?

**Comment by jaimiebutton** [comment]
Sure I would love that, thank you @Dianadec !

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - this should be your primary focus for the rest of the sprint and to include KS's comments :)

**Comment by LindsayMacfarlane** [comment]
It looks sooo good @jaimiebutton !Well done. I have forwarded to CF,ES and KS for last comments.
