### ISSUE TITLE
Loop in STB

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#16]
Feedback is a powerful thing. Following [ticket #6](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/6) to loop in CG stakeholders, we'd also like to pass our project plan along to ENV's Service Transformation Branch.

- [x] Schedule meeting with STB
- [x] Show project plan
- [x] Document feedback in Teams channel

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - is this a ticket that I can support you on? I have regular check-ins with JC and can provide a quick update.

**Comment by jaimiebutton** [comment]
Hi Lindsay, sure! Would you want to walk through the project plan in an upcoming checkin?

**Comment by LindsayMacfarlane** [comment]
Yeah, that was what I was thinking (if that works for you?). Just thinking how we can make things efficient for JC and use her time wisely.
