### ISSUE TITLE
Review CAS/ENV digital strategies for relevant alignment

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#17]
The ENV & CAS Digital Strategies offer a ton of alignment with this project. This task captures the identification of relevant digital goals and opportunities outlined in the strategies.

- [x]  Review CAS digital strategy
- [x] Review ENV digital strategy
- [x]  Create documentation of relevant points
- [x]  [Upload documentation](https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fbcgov.sharepoint.com~2Fteams~2F00608-PublicReporting~2FShared%20Documents~2FPublic%20Reporting~2FAlignment%20with%20CAS%20Digital%20Strategy.docx?threadId=19:4323bfce17a441b99c170068f16dd4a9@thread.tacv2&baseUrl=https:~2F~2Fbcgov.sharepoint.com~2Fteams~2F00608-PublicReporting&fileId=98d985dd-587e-4b4c-aef9-810217c02f11&ctx=files&rootContext=items_view&viewerAction=view) to Public Reporting Teams channel

**Comment by LindsayMacfarlane** [comment]
Awesome - thank you @jaimiebutton ! I've left a couple of comments in the document for your consideration, namely:
1) This obviously aligns with the digital strategy, but it is so much more than simply digital...but also services. How can we ensure we keep this in mind?
2) Perhaps a separate task, but it would be good to also align to the roadmap to 2030. 
3) How do we bring this all together in a nic visual way: e.g., digital strategy, Roadmap, etc? Thinking ahead to future presentations.
4) Can we use any of these goals/alignment opportunities to our KPIs?
