### ISSUE TITLE
Review current public reporting spreadsheets

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#18]
Public industrial emissions data currently lives BC Gov webpages. 

- [x]  Review [Industrial facility greenhouse gas emissions](https://www2.gov.bc.ca/gov/content/environment/climate-change/data/industrial-facility-ghg#:~:text=Data%20from%202020%20shows%20the,2e%20reported%20in%202019) (one file per year)
- [x]  Review [Provincial greenhouse gas emissions inventory](https://www2.gov.bc.ca/gov/content/environment/climate-change/data/provincial-inventory)

Definition of done:
- Understanding of the types of gases in the spreadsheets
- Understanding of the types of operations (LFO, SFO)
- Understanding of the kind of data available

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - ES can get us analytics related to site access for https://www2.gov.bc.ca/gov/content/environment/climate-change/data/industrial-facility-ghg

**Comment by jaimiebutton** [comment]
Beauty, thanks @LindsayMacfarlane! I've added this ticket to capture the site analysis work: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/38

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - for consideration on this ticket, will you need RAU staff time to ask questions and have them walk you through the data that is there?

**Comment by jaimiebutton** [comment]
Interesting note from [Provincial Inventory (1990-2019)](https://www2.gov.bc.ca/gov/content/environment/climate-change/data/provincial-inventory#:~:text=In%202019%2C%20British%20Columbia's%20gross,for%20our%20emission%20reduction%20targets.)

*This is the gross total. BC's progress to its GHG emissions reduction targets is calculated using the net total, which also includes emissions reduction offsets from forest management projects.*

I wonder how this aligns with the dataset currently being used to calculate our progress to 2030 targets?

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - do you have any write up/documentation that provides a synopsis of the different reporting and how they align or differ?

**Comment by LindsayMacfarlane** [comment]
Thank you for your update during sprint review @jaimiebutton - closing ticket.
