### ISSUE TITLE
Intro to Service Design

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#20]

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - did we want to tackle this next sprint (May 16 - 27)? Wondering if we want to do this sooner than later? Do we want to only focus on ES or include others like AF, CF, others?

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane - I have a feeling next sprint will be pretty busy with research planning, but we can flesh out a preparation ticket in case we have extra time. We don't need to deliver the intro to service design but we could get some materials ready ;)

Who would you recommend, participation-wise?

**Comment by LindsayMacfarlane** [comment]
Note: not completed during initial research and discovery phase. Removed from Team Training EPIC to capture in potential future work.

**Comment by jaimiebutton** [comment]
Closing this ticket as it's no longer relevant
