### ISSUE TITLE
How do we bring the program area along on this journey? Specifically, how do we share/teach the business about how we do this work = empower them for future projects?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#21]

**Comment by LindsayMacfarlane** [comment]
Closing ticket. Although not directly addressed - the process and communication channels established for the project team helped to address this question. Key program area staff were invited to all stakeholder sessions, MS Teams channel was set up for quick and easy sharing of documentation/questions/feedback. Regular touchpoints established.
