### ISSUE TITLE
Review Tableau

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#22]
The open data in Tableau has show the potential for using emissions data in a more user-friendly way. We want to make sure we build off this work, not skip over it.

#### Acceptance Criteria:
- [x] Review public Tableau 
- [x] [Document thoughts & questions](https://public.tableau.com/app/profile/irc.gc.cas.bc/viz/BCIndustrialGHGPublicReports18-Oct-2021/Main)

#### BONUS
- Can we find analytics on who has looked at the site? (see comment below)

#### Notes
- Tableau site: https://public.tableau.com/app/profile/irc.gc.cas.bc/viz/BCIndustrialGHGPublicReports18-Oct-2021/Main

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - I've reached out to ES and she will look to see if there are any analytics associated with the tableau site.

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton ! I found your analysis very helpful and your questions/comments very insightful. In relation to the 'bonus' - finding analytics on the tableau site, is that we should still follow up on?
