### ISSUE TITLE
BC's Climate Change Targets

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#23]
Emissions data connects to so many things in gov - and as a result, we want to make sure we have an understanding of the current climate targets & communication surrounding them.

**Acceptance criteria:**
- [x] Read BC Gov's[ Climate action and accountability](https://www2.gov.bc.ca/gov/content/environment/climate-change/planning-and-action) webpage
- [x] [Document ](https://bcgov.sharepoint.com/:w:/r/teams/00608/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Project%20Resources/Looking%20at%20BC%E2%80%99s%20Climate%20Change%20Targets.docx?d=wad1002be06cc4a38a086802e67be56cf&csf=1&web=1&e=2qV7e3)findings & questions

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, do you know which team is responsible for [this page](https://www2.gov.bc.ca/gov/content/environment/climate-change/planning-and-action/progress-targets 
)? It would be helpful to have a conversation with them.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - I believe that is done by the folks with the Accountability Report - we could reach out to Jenn Turner.
