### ISSUE TITLE
Prepare Stakeholder Mapping Session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#25]
Many stakeholders are involved in this project. To kick the work off, we will map out the stakeholders we know of.

**Acceptance criteria:**
- [x] Schedule stakeholder mapping session
- [x] Design session
- [x] Get feedback from GGIRCS team
- [x] Make tweaks based on feedback

**Comment by LindsayMacfarlane** [comment]
Beauty. Thanks @jaimiebutton - I'm super excited for the stakeholder mapping session!
