### ISSUE TITLE
Review BC Policy approaches playbook

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#28]
Acceptance criteria:

 - [ ] Read BC's [Policy Approaches Playbook](https://www2.gov.bc.ca/assets/gov/government/about-the-bc-government/regulatory-reform/pdfs/policy_approaches_playbook.pdf)
 - [ ] Document findings & questions

**Comment by LindsayMacfarlane** [comment]
Note: not completed during initial research and discovery phase. Removed from Internal Research EPIC to capture in potential future work.

**Comment by jaimiebutton** [comment]
Closing this ticket as it's no longer relevant
