### ISSUE TITLE
Digital Literacy

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#31]
#### Description:
Encourage program area to take digital leadership training at onset of project to help with expanding knowledge and experience with digital service concepts and processes.

#### Checklist:
- [x] Find potential opportunities
- [x] Send to PR team for consideration

#### Notes:
- We are also looking at leading digital leadership training for CAS executive and managers during the summer/early fall, so there will be opportunity there as well.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - not yet. @Sriram-pc, can you see if there are any upcoming training opportunities that we can let project team know about?

**Comment by Sriram-pc** [comment]
Hi @LindsayMacfarlane, 
1) There is a Agile Fundamentals course which should be good. But seats are on waitlist.
https://learningcentre.gww.gov.bc.ca/learninghub/learning_partner/digital-academy/

2) How to develop a digital mindset in government. Self Directed
https://learningcentre.gww.gov.bc.ca/learninghub/course/how-to-develop-a-digital-mindset-in-government/

These are from Digital Academy (learning Hub). I will look for more.

**Comment by Sriram-pc** [comment]
There is also a Introduction to Digital Era Leadership
This is a day long webinar.
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/ad395a89-0e82-4134-8c77-28522ed7ef63)

**Comment by Sriram-pc** [comment]
Another one from Apolitico : , How to lead digital transformation in the public service, on Tuesday 5 July, 2-2:45pm BST / 9-9:45am EDT
@LindsayMacfarlane 
https://docs.google.com/document/d/134wwq9tPgEjj5YEsbSxeQrkwJPfCud7c7lC4i3yFrv4/edit

**Comment by LindsayMacfarlane** [comment]
These are great. Thank you @Sriram-pc.

**Comment by LindsayMacfarlane** [comment]
I'm going to consider this ticket closed. I did send out an email to CF, ES and others in CAS about training opportunities several months ago.
