### ISSUE TITLE
Hold stakeholder mapping session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#34]
This ticket follows [ticket #25](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/25) to plan the stakeholder mapping session.

**Acceptance Criteria:**
- [x] Hold first stakeholder mapping session with Clean Growth stakeholders
- [x] Hold second stakeholder mapping session
- [x] Document next steps
- [x] Pass back findings of session afterward

Following this session, we can use the list generated to start to plan outreach and research activities.

**Comment by LindsayMacfarlane** [comment]
Note: second session was scheduled during this sprint in order to complete stakeholder prioritization.

**Comment by LindsayMacfarlane** [comment]
Great work @jaimiebutton - as always, your session was meticulous and well designed. I appreciated the feedback from the program area - who were worried we wouldn't have enough people to engage - now we may have too many! I'm excited for the next stage where we get to start going out and talking to various stakeholder groups.
