### ISSUE TITLE
"This project in a nutshell" document

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#35]
It can often be hard to succinctly explain the scope and value of a project - but we know clear visuals help! This ticket captures work to create a simple document explaining what this project is and why we're doing it to send or show to interested parties when asked.

**Acceptance Criteria:**
- [x] Ideate what needs to go into this document
- [x] Create document
- [x] Pass to project team for feedback
- [x] Iterate on feedback
- [x] [Convert deck to PPT](https://bcgov.sharepoint.com/:p:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Presentations/The%20Public%20Reporting%20Project.pptx?d=wce66e4ccb49747e4948164567e06fc4c&csf=1&web=1&e=cRAZPI)
- [x] Put in Public Reporting Teams channel

**Comment by jaimiebutton** [comment]
Relevant note from @LindsayMacfarlane: 

> "Something I've observed in recent meetings is there may be slight confusion around our project name of "Public Reporting". There may be a perception that we are focusing on the 'public' during our engagement vs understanding how industry and citizen's access our data. Just something to be aware of. We should consider creating an elevator pitch and project vision that we can communicate out."

**Comment by jaimiebutton** [comment]
Can also consider mentioning value delivered vs [value realized](decisionlink.com/value-realization)

**Comment by LindsayMacfarlane** [comment]
Thank you so much @jaimiebutton ! It is such a great idea to have a deck ready and on the go to help with future presentations.
