### ISSUE TITLE
Indigenous Consultation Training

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#37]
#### Description:
Find opportunities to take indigenous relations courses to help support our understanding of culturally appropriate communication and consultation.

#### Checklist:
- [x] Set up '[Working Effectively With Indigenous Peoples](https://www.indigenousrelationsacademy.com/collections/self-guided-training/products/working-effectively-with-indigenous-peoples-self-guided-training)' training
- [x] Complete chapter 1-5
- [x] Complete chapter 5-10
- [x] Complete chapter 10-17
- [x] Document learnings in[ shared word doc](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Reference%20Documents/Working%20Effectively%20with%20Indigenous%20Peoples.docx?d=wea170d4d67ee45a2b853b4e4b27af529&csf=1&web=1&e=h9L3N8)

#### Other courses available:

- [Trust and Reconciliation ](https://learning.gov.bc.ca/psc/CHIPSPLM_6/EMPLOYEE/ELM/c/LM_OD_EMPLOYEE_FL.LM_FND_LRN_FL.GBL?Page=LM_FND_LRN_RSLT_FL&Action=U&KWRD=%22ITEM-1731%22&)
- [Through the Lense of Reconciliation ](https://learning.gov.bc.ca/psc/CHIPSPLM_6/EMPLOYEE/ELM/c/LM_OD_EMPLOYEE_FL.LM_FND_LRN_FL.GBL?Page=LM_FND_LRN_RSLT_FL&Action=U&KWRD=%22ITEM-1277%22)
- [Building Capacity in Indigenous Relations: We are all here to stay](https://learning.gov.bc.ca/psc/CHIPSPLM_6/EMPLOYEE/ELM/c/LM_OD_EMPLOYEE_FL.LM_FND_LRN_FL.GBL?Page=LM_FND_LRN_RSLT_FL&Action=U&KWRD=%22ITEM-5%22)

#### Notes:
- The majority of the listed courses above are offered through the Learning Centre/PSA. They may be IDIR restricted.

**Comment by jaimiebutton** [comment]
Recommendations from Julia H - Research & Policy Analyst can be found in [Teams files here](https://bcgov.sharepoint.com/:w:/r/teams/00608/Shared%20Documents/Public%20Reporting/Resources/Indigenous%20Relations%20%26%20Organizations%20-%20From%20Julia%20H.docx?d=w7649150efa1a49f2ab3e85e63b783fb9&csf=1&web=1). 

The following course was also recommended: https://www.indigenousrelationsacademy.com/collections/self-guided-training/products/working-effectively-with-indigenous-peoples-self-guided-training

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I'm so happy you were able to take this course.
