### ISSUE TITLE
Review GHG Inventory Site Analytics

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#38]
Much of our public data lives in [this BC Gov site](https://www2.gov.bc.ca/gov/content/environment/climate-change/data/industrial-facility-ghg). In addition to reviewing the files themselves as documented in [Ticket #18](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/18), we can also review the site analytics to understand how often this information is accessed.

**Acceptance Criteria:**
- [x] Receive analytics from ES, including [Summary](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Analytics/Summary%20of%20GHG%20Page%20Analytics.docx?d=wfecc4dd469eb49e094ddd8ee515e69e0&csf=1&web=1&e=3IjFJe) and[ PDF Report](https://bcgov.sharepoint.com/:b:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Analytics/Industrial%20facility%20greenhouse%20gas%20emissions%20Page%20Analytics%202022-04-26.pdf?csf=1&web=1&e=74j8KX)
- [x] Review & analyze async
- [x] [Document](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Analytics/Summary%20of%20GHG%20Page%20Analytics.docx?d=wfecc4dd469eb49e094ddd8ee515e69e0&csf=1&web=1&e=zLKho2) & share findings
- [x] Pass data requests to Emilie for follow-up

**Comment by jaimiebutton** [comment]
@elliottSlee, would you be able to help analyze this data?

**Comment by elliottSlee** [comment]
I took a look and there isn't much to be analyzed here. I'd love to help summarize it and fit it into the context of the project.

**Comment by jaimiebutton** [comment]
Thank you! I've refined the criteria above to review & summarize async. I'll schedule this ticket for next sprint and assign us both.

**Comment by elliottSlee** [comment]
Posted in [Teams](https://teams.microsoft.com/l/message/19:514748d66add464cb5f05b69e144ca20@thread.tacv2/1651510028161?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=29821293-3244-455d-beae-e01d27762cfe&parentMessageId=1651510028161&teamName=External%3A%20CAS%20-%20Digital%20Service%20Team&channelName=Public%20Reporting&createdTime=1651510028161): 

The site analytics offer some really interesting insights. 

1. Referrals -- the top is no referral which counts several things: something wasn't logged correctly, users had do not track enabled or is using a VPN/proxy/firewall, the most common is search engine crawlers just checkin in on the site, but maybe more interesting is the people who accessed directly (i.e., typed in the url, had it bookmarked, or from an email). Unfortunately it's impossible to figure out which of these categories the 1,396 page views fall into.
2. VERY IMPORTANT -- there were 9 views between midnight on a Saturdays and 5am Sundays! Who? What? Why?
3. Mapping data - Most of the access is coming from cities. I don't see anything that could be from facilities. From this, it's hard to discern who is accessing.
- There is access from Seattle, Idaho (maybe Moscow, Idaho?), and possibly Portland but I can't see it in the map provided. Why is there traffic from the US? VPN? Companies? Climate scientist? Activists? Journalists?
5. I find it odd that downloads of a 2018 report is the highest--by a large margin. Why might this be? 
- Can we get access to these analytics to check when these downloads took place? Was is when this report was released in 2019 or has it been spread over 3 years?
6. The actual most important thing I noticed: Traffic has a clear pattern of highest activity in November and March. Why might this be? What deadlines exist for companies or other stakeholders?		
8. GHG reports are due May 31st, CIIP is due June 30th, CIF is due June 3rd. So not those.

**Comment by jaimiebutton** [comment]
Update: Additional data requests passed to Emilie for follow-up

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton! I noticed we are storing the analytics info on our private channel. What are your thoughts about moving that information to our open MS Teams Channel?

**Comment by jaimiebutton** [comment]
@LindsayMacfarlane Sounds good to me!
