### ISSUE TITLE
Get overview of CleanBC & GoElectric Project

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#39]
Acceptance Criteria:
- [x] Schedule session with Jenna from CleanBC/GoElectric Project
- [x] Hold session
- [x] Record takeaways in comments below

**Comment by jaimiebutton** [comment]
_Session notes:_

1. **What was the GoElectric Project?**
- Increasing traffic to program site and overall program usage related to incentives for purchasing electric vehicles
- Research & design project with overall website redesign deliverable

2. **What was the CleanBC project?**
- Refers to government’s 2030 plan. One big goal was to go from a marketing plan for the 2030 plan PDF to a gathering place that people know about → connects one CleanBC service to another CleanBC services
- Combining information as a service, transaction as a service, and being able to provide feedback to gov

3 **How did they handle recruitment & research activities?**
- Call for participants on website, shared on linkedin etc.
- Then someone filters through and qualified people
    - Age, geography, housing type, age
- Really good content strategy with a list of range of climate change beliefs that they were willing to talk to
    - Identified they wouldn’t talk to climate change skeptics & extreme beliefs
- 60 minute interviews
    - 30 minute interview, 30 minute clickable prototype
    
4. **Next steps**
- Ask Meg S. for access to GoElectric research Mural board

5. **Connect to 2030 goals?**
- There’s a connection there found in research
- They made a User Story that’s “as a user, I want to know how on track we are to 2030 goals”

6. **Can also connect us to folks from a disclosure project:**
- Municipal workers that manage disclosure programs for their municipality
- Building managers who own a private building that are disclosing data
- Prov/Fed government comes in with regulation and funding for execution of programs

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton - I know a really high level overview of this project, but I look forward to learning more. Can you confirm that this information has been captured in our overall documentation (not just in ZenHub)?
