### ISSUE TITLE
PIA: Explain how participants were identified

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#40]
Following the creation of our PIA, we need to be ready to answer how we we are planning on consulting the public and how participants were identified.

**Acceptance Criteria:**
- [x] Write few-sentence answer
- [x] Document that answer 

**Notes:**
Can include engagement through academia, people industry & gov already engages with, word of mouth, public surveys

**Comment by jaimiebutton** [comment]
"Participants were selected by identifying user groups and prioritizing them based on level of interest and impact for the project. Following a snowball research process, additional participants were also identified by asking interviewees for recommendations of who else to talk to."

@LindsayMacfarlane What are your thoughts on this?

**Comment by LindsayMacfarlane** [comment]
Love it @jaimiebutton. We might also want to add that when we talk about 'public' the focus is more on public groups such as NGOs, academia, etc.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - FYI, I added a slide in the deck to capture this information re. how participants were identified.
