### ISSUE TITLE
Are we showing any data through DataBC?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#41]
DataBC holds much of BC Gov's public data. This begs the question - is any of our industrial emissions data included in Data BC's Catalogue? Let's find out!

**Acceptance criteria:**
- [x] Find out if we are showing any data through Data BC's Catalogue
- [x] Document that answer (perhaps need a space on Miro capturing places our data is used?)

**Comment by LindsayMacfarlane** [comment]
I found the following datasets, but it is unclear to me if they contain any of our data. I have message ES for clarification.

https://catalogue.data.gov.bc.ca/dataset/british-columbia-greenhouse-gas-emissions-archive
https://catalogue.data.gov.bc.ca/dataset/british-columbia-greenhouse-gas-emissions
https://catalogue.data.gov.bc.ca/dataset/bc-greenhouse-gas-emissions-individual-facilities-summary (this looks like ours?)
https://catalogue.data.gov.bc.ca/dataset/bc-greenhouse-gas-emissions-electricity-import-summary (this looks like ours?)
https://catalogue.data.gov.bc.ca/dataset/bc-greenhouse-gas-emissions-linear-facilities-summary (this looks like ours?)

**Comment by LindsayMacfarlane** [comment]
Document of results, recommendations and next steps added to the public 'Public Reporting' MS Teams Channel.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - let me know if there is more detail or info that I can provide related to this ticket. I haven't yet captured the next steps in ZenHub tickets as I'd like to discuss approach first.

**Comment by jaimiebutton** [comment]
Hi Lindsay, thanks for this work! 

- Reach out to DataBC to get analytics on Clean Growth datasets to determine usage 
- Reach out to DataBC to update or remove old CG datasets 
- Work with other CAS branches to clean up their datasets?  
- Work with IRC to get spreadsheet (or CIIP data published) – will need to scope out/understand how this can be done 

Of the action items you identified, what do you think about creating tickets for the first two bullets, or maybe just the first? They seem to be lower-hanging fruit.

**Comment by LindsayMacfarlane** [comment]
Sounds perfect @jaimiebutton. I will get those created.
