### ISSUE TITLE
Connect with CleanBC project team

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#42]
We were recommended by ENV's Service Transformation Branch to contact the CleanBC project team as they have similar parallels in their work with data reporting.

**Acceptance Criteria:**
- [x] Contact Meg S.
- [x] Get access to Teams channel
- [x] Get access to CleanBC sprint reviews
- [x] Set up conversation with Meg S.
- [x] [Document learnings from conversation](https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fbcgov.sharepoint.com~2Fteams~2F00608~2FShared%20Documents~2FCleanBC%20Notes.docx?threadId=19:514748d66add464cb5f05b69e144ca20@thread.tacv2&baseUrl=https:~2F~2Fbcgov.sharepoint.com~2Fteams~2F00608&fileId=d137432a-6685-4ee9-b41c-e1703f3064d5&ctx=files&rootContext=items_view&viewerAction=editNew)

**Notes:**
Conversation can include understanding the scope of the CleanBC project, relevant research we can build upon, lessons learned, and recommendations of other people we can talk to.

**Comment by LindsayMacfarlane** [comment]
Meeting with Meg set up for May 9, 2022.

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - I've invited Meg to our Teams Channel as per one of the action items from our conversation. Can we consider this ticket complete or are there any outstanding follow up actions?

**Comment by jaimiebutton** [comment]
Just moved to PO column, good timing ;)
