### ISSUE TITLE
Loop in Nan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#46]
Welcome to the team, Nan! Let's get you onboarded with the Public Reporting project.

**Acceptance criteria:**
- [x] Book call
- [x] Run through project plan
- [x] See where in plan Nan can/would like to help

**Comment by jaimiebutton** [comment]
Hey @nanyangpro @LindsayMacfarlane, here are some takeaways from our conversation:

**Where Nan can help:**
- User Research
- UI Design
- UX Design
- Graphic design
- Peer review
- Presentations with external/external stakeholders
- Video editing

**Also interested in:**
- Participating in conversations with stakeholders

**Comment by jaimiebutton** [comment]
Hey @nanyangpro @LindsayMacfarlane, here are some takeaways from our conversation:

**Where Nan can help:**
- User Research
- UI Design
- UX Design
- Graphic design
- Peer review
- Presentations with external/external stakeholders
- Video editing

**Also interested in:**
- Participating in conversations with stakeholders

**Comment by nanyangpro** [comment]
Looks great! Thanks @jaimiebutton

**Comment by LindsayMacfarlane** [comment]
Thank you so much @jaimiebutton @nanyangpro. Nan - I'd love to get your pick your brain on graphic design and branding!

**Comment by nanyangpro** [comment]
Sounds great, @LindsayMacfarlane ! Shall we book an 1-hour meeting? (I'd also love to learn more about the epics and research/design-related tickets from you. :) I'm open next  Monday afternoon.
