### ISSUE TITLE
Create BC Gov Contact Tracker

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#52]
This project involves a lot of outreach to folks in the BC Government. We'll need a way to store all this contact info and track our progress.

**Acceptance Criteria:**
- [x] Create tracker
- [x] Fill tracker with contacts we'd like to and have reached out to
- [x] Keep tracker[ in Teams channel](https://bcgov.sharepoint.com/:x:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/User%20Engagement/Contact%20Tracker.xlsx?d=w0b20c88543ad471cbc17fd8417e0a46a&csf=1&web=1&e=7zzmWe) to continually refer back to

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton! This will be helpful to track and report out on at a high level. A couple of questions/comments:

- Will there be a tab to represent each stakeholder group (align with our stakeholder mapping session)?
- What are your thoughts on including a column to indicate an individuals level of interest/engagement in the project?
- We should ensure how we are tracking and where we are storing this information aligns with our PIA (I believe it does at this time, but we will want to double check when we add in any potential private information).

**Comment by jaimiebutton** [comment]
Thanks for your thoughts on this, @LindsayMacfarlane! Do you know what our PIA says about storing this kind of information?
