### ISSUE TITLE
First round of engagement - CAS Staff

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-public-reporting#57]
#### Describe the task

Reach out to first group of CAS & EMILI staff to get an understanding of their perspectives on access to climate related data. 

#### Acceptance Criteria

- [x] Reach out to staff & book sessions
       - Nancy
       - Hilary
       - Robb
- [x] Develop questions
- [x] Hold session
- [x] Document feedback

**Comment by LindsayMacfarlane** [comment]
FYI @jaimiebutton - I added Rob T to this ticket, which I'm assuming we will want to start next sprint?

**Comment by jaimiebutton** [comment]
Thanks @LindsayMacfarlane, adding Robb here is a great call!

**Comment by LindsayMacfarlane** [comment]
Thank you so much @jaimiebutton ! This first round was fantastic and a great start to user engagement.
