### ISSUE TITLE
Internal Research Planning: Participants

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#58]
This project will follow research methods outlined in the BC Gov Service Design playbook.

**Acceptance Criteria:** 
 - [x] Identify research participants for internal BC Gov research
 - [x] Get feedback from project team
- [x] Iterate on feedback if needed

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton ! I'm so excited for more discovery sessions :)
