### ISSUE TITLE
Internal Research Planning: Recruitment

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#59]
This project will follow research methods outlined in the BC Gov Service Design playbook.

Acceptance Criteria:

 - [x] Identify recruitment methods of BC Gov internal research participants
 - [x] Coordinate who on project team will contact each participant

**Comment by LindsayMacfarlane** [comment]
So excited for this next phase and going out to talk with users! As always, thank you for all your hard work on this @jaimiebutton
