### ISSUE TITLE
Add stickies from Stakeholder Map to Excel

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#60]
Stakeholder mapping for government & industry stakeholders was completed last sprint. This ticket documents adding stakeholders identified from those categories to the team's [Contact Tracker ](https://bcgov.sharepoint.com/:x:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/Stakeholder%20Engagement/Contact%20Tracker.xlsx?d=w0b20c88543ad471cbc17fd8417e0a46a&csf=1&web=1)excel sheet.

**Acceptance Criteria:**
- [x] Add missing stakeholders to excel sheet
- [x] Track who referred them

**Comment by LindsayMacfarlane** [comment]
Hi @Sriram-pc - are you able to support @jaimiebutton on this task? If so, perhaps follow up directly and see what needs doing. Thanks!

**Comment by jaimiebutton** [comment]
Hey @Sriram-pc that would be great, thank you! Any information you don't see there, feel free to leave blank and I can add it in.

**Comment by Sriram-pc** [comment]
I have added the available information to the contact tracker. Mainly Name (Company or person), Context and Level of Engagement are the info that are available. I have added that to the tracker.

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - Ram has added in available info into the tracker. Can you confirm if this ticket is now complete?

**Comment by LindsayMacfarlane** [comment]
Thanks so much @jaimiebutton and @Sriram-pc - this will certainly be an on-going task throughout the project.
