### ISSUE TITLE
Connect with EMLI

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#62]
The Ministry of Energy, Mines, and Low Carbon Innovation (EMLI) is responsible for BC’s electricity, alternative energy, mining and petroleum resource sectors, and supporting work to meet BC’s greenhouse gas reduction targets. 

- [x] Set up calendar invite
- [x] Write questions for conversation
- [x] Get feedback on questions

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton !
