### ISSUE TITLE
Connect with FLNRO

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#63]
The Forests, Land, and Natural Resource Operations (FLNRO) ministry is responsible for the stewardship of provincial Crown land and ensures the sustainable management of forest, wildlife, water and other land-based resources. The Ministry works with Indigenous and rural communities to strengthen and diversify their economies.

- [x] Set up calendar invite with Nora W

**Comment by jaimiebutton** [comment]
Putting back in the backlog for when we do hear back :)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
