### ISSUE TITLE
Connect with OGC

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#65]
The BC Oil & Gas Commission (OGC) is a single window regulatory agency with responsibilities for overseeing oil, gas and renewable geothermal operations.

_(Single window are platforms that are government mandated and allow for the submission of information to fulfill regulatory requirements between economic operators and government authorities)_

- [x] Set up calendar invite
- [x] Write questions for conversation
- [x] Get feedback on questions

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - just clarifying, this is the interview that has been postponed until July?

**Comment by jaimiebutton** [comment]
Hey Lindsay, yes. We have another ticket for conducting the conversation that I'll keep in our backlog until then :)
