### ISSUE TITLE
GBA+

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-public-reporting#67]
#### Describe the task

Get a better understanding of how we can apply a GBA+ lens to our research related to public reporting. 

#### Acceptance Criteria

- [ ] GBA+ training (note: there is a free course offered by the Federal Govt)
- [ ] Reach out to staff with GBA+ experience ( e.g., Jessica K, Emma S, Jackie D)
- [ ] Document how we can apply it to our research

**Comment by suhafa** [comment]
I finished some GBA+ training recently, and if it helps, [**here are some notes**](https://buttoninc.notion.site/Introduction-to-GBA-course-651dc96bd75242db8ed9c333130b31e7) I took during the session. Some of the notes are directly borrowed from the course.

**Comment by LindsayMacfarlane** [comment]
Note: not completed during initial research and discovery phase. Removed from Internal Research EPIC to capture in potential future work. Moved ticket to icebox.

**Comment by jaimiebutton** [comment]
Closing this ticket as it's no longer relevant
