### ISSUE TITLE
Hold Conversation with OGC

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#69]
The project team will be meeting with Josh C. from the OGC on June 14.

Acceptance Criteria:
- [x] Hold conversation 
- [x] Save recording in Teams channel
- [x] Document findings in Teams channel

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - let's close this one off :)

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - do you remember off hand what sprint this was completed in?

**Comment by jaimiebutton** [comment]
@LindsayMacfarlane Yes! It was July 11.
