### ISSUE TITLE
Hold Conversation with EMLI

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#70]
The project team will be meeting with Garth T. on June 9 and Geoff T. on June 15.

Acceptance Criteria: 

June 9
- [x] Hold conversation with Garth
- [x] Save recording in Teams channel
- [x] Document findings in Teams channel

June 15
- [x] Hold conversation with Geoff
- [x] Save recording in Teams channel
- [x] Document findings in Teams channel

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I really enjoyed the conversation with Geoff - super informative.
