### ISSUE TITLE
Hold Conversation with FIN

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#71]
The project team will be meeting with Kara F. and Lynn H. from FIN on June 15.

Acceptance Criteria:
- [x] Hold conversation 
- [x] Save recording in Teams channel
- [x] Document findings in Teams channel

**Comment by jaimiebutton** [comment]
Note: Lynn did not join us

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
