### ISSUE TITLE
Write email for Industry Associations

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#72]
Our next phase will be talking to Industry associations. 

Acceptance Criteria:
- [x] [Write draft email ](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Outreach%20Templates/Intro%20Email%20to%20Industry%20Associations.docx?d=w0b9c9e31549444499ce847df941773b5&csf=1&web=1&e=VZBZVQ)to send to industry associations
- [x] Send draft to team for feedback
- [x] Pivot on feedback if necessary
- [x] Share with wider project team

**Comment by jaimiebutton** [comment]
Hi @LindsayMacfarlane, do you have any feedback on the email to industry associations linked above?

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - I've included feedback in the word document. We should probably circulate to Chris/Emilie for feedback/input as well.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - Feedback received from Chris. Closing ticket based on sprint planning discussion. Thank you for drafting!
