### ISSUE TITLE
Connect with ENV Indigenous Consultation Experts

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#74]
To start the journey of contacting indigenous organizations, the team will reach out to internal resources for support.

Acceptance Criteria:
- [x] Reach out to CAS contact (Lindsay)
- [x] Reach out to Amanda Punshon from CleanBC Project (Jaimie)

**Comment by jaimiebutton** [comment]
Update (@LindsayMacfarlane) - sent email to Amanda Punshon from CleanBC/GoElectric who I've heard has some valuable recommendations for indigenous consultation. Hoping to set up a chat over the next couple weeks!

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton - for my clarification, do we have a ticket in the design backlog to capture the actual conversation with these individuals?
