### ISSUE TITLE
Read 'What we heard - Clean BC Roadmap'

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#76]
Katie M-S provided a copy of the report titled: "What we heard: Engagement with Indigenous Peoples on the CleanBC Roadmap to 2030" ([link to report can be found here](https://bcgov.sharepoint.com/:b:/r/teams/00608/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Project%20Resources/what_we_heard_-_cleanbc_roadmap_to_2030_development.pdf?csf=1&web=1))

- [x] Read report
- [x] Add comments & questions to [note-taking doc](https://bcgov.sharepoint.com/:w:/r/teams/00608/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Project%20Resources/What%20we%20heard_Notes.docx?d=wea0e86667c9c4ec197aed278dadf21d4&csf=1&web=1)

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - given our conversation with Katie is next week, do you want to pull this ticket into this sprint?

**Comment by jaimiebutton** [comment]
You got it :)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
