### ISSUE TITLE
Create interview guides for Industry Association conversations

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#77]
Following[ ticket #75](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/75), create interview guides for industry association conversations.

**Acceptance Criteria:**
- [x] Create template document
- [x] Add questions to documents
- [x] Pass to project team for additions
- [x] Add note about privacy statements for industry association stakeholder sign off

Note:
- Duplicate template document as needed

**Comment by jaimiebutton** [comment]
Hi @LindsayMacfarlane , was there a specific action item here for the privacy statements?

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
