### ISSUE TITLE
Research Analysis: Patterns in BC Gov Interviews

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#78]
Following interviews with a series of BC gov stakeholders, conduct research analysis to find patterns and common themes

**Acceptance criteria:**
- [x] Review note-taking docs for each conversation
- [x] Document patterns and themes in Miro
- [x] Share findings with project team

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - will part of this work look at quantifying the feedback received to date? How do you propose to document the feedback/theme's (e.g., miro? word?). As part of this ticket, should we also add a slide to our deck that captures the initial findings?

**Comment by jaimiebutton** [comment]
Thanks Lindsay! I'm thinking to keep it qualitative for now as we haven't had many interviews to quantify yet but thinking we can use the Miro space as a place to build off as we keep interviewing. I'll include answers to your questions in the ticket.

**Comment by LindsayMacfarlane** [comment]
Thank you for all your hard work @jaimiebutton
