### ISSUE TITLE
Outreach to other provincial governments

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#79]
Provincial governments doing similar work to us may have a lot of valuable insight to share! This ticket follows [#80](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/80) which documents the creation of an outreach email.

**Acceptance Criteria:**

- [x] Send email to the following contacts as outlined in [this Teams document](https://bcgov.sharepoint.com/:w:/r/teams/00608-PublicReporting/Shared%20Documents/Public%20Reporting/2.%20Implementation%20Phase/Reference%20Documents/Relevant%20Provincial%20Contacts.docx?d=w8c0ee875bf45402da65236ffe57e6931&csf=1&web=1&e=O30A71):
- Ontario Government
- Quebec Government
- PEI Government

**Conversation Goals:**
- Validate that we have similar problems with our data
- Understand similar initiatives to ours
- Gather ideas of what we could do with the data
- Capture recommendations of people to talk to or existing good examples

**Comment by LindsayMacfarlane** [comment]
Looks good @jaimiebutton ! Perhaps this will be captured as part of #80, but what will be the intent/outcome that you hope to achieve through this outreach? Ie;, a follow up discovery session? sharing of material? etc. I'm assuming Chris has contacts as well for these governments?

**Comment by jaimiebutton** [comment]
I'll add that to the ticket, thanks :)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton - I look forward to learning more about what other province's are doing in this realm.
