### ISSUE TITLE
Reach out to UBC/SFU Contacts

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#84]
#### Description ####
As part of the public reporting project, reach out to identified key stakeholders at Simon Fraser University to better understand their use and need for industrial greehouse gas emissions data. 

#### Checklist ####
- [x] Identify key stakeholders
- [x] Draft email
- [x] Send email to UBC contacts
- [x] Send email to SFU contacts

#### Notes ####

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I'd recommend if you don't hear back within the week that you just send out meeting invites to our SFU contacts.
