### ISSUE TITLE
Map where our dataset is currently being used in BC Gov

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#85]
Through a series of interviews with BC Gov employees, we've uncovered which teams are and are not currently using our data. This ticket documents creating a map of where our data currently IS being used as a current state analysis tool.

**Acceptance Criteria:**
- [x] Compile a list of teams that are currently using our dataset
- [x] Create a visual representation on Miro to show dataset usage

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - can you explain this one? Is this this mapping out each Ministry and who uses - i.e., putting the research into a more visual context?

**Comment by jaimiebutton** [comment]
Haha! Any other questions left unanswered from the description?

**Comment by jaimiebutton** [comment]
Update: I scoped down this ticket to create a quick graph of which teams were using our dataset as there was a good amount of overlap with [ticket #86](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/86)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton. It is wonderful to see the research start to be pulled together for analysis and insight.
