### ISSUE TITLE
Map of BC Gov research participants' relationship to our dataset

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#86]
From internal research conducted with BC Gov employees, there seem to be 3 distinguished categories of BC Gov teams - those who are currently using our data, those who are aware of it, and those who were unaware. This ticket captures the creation of a map to visually represent these 3 core relationships. This deliverable can be iterated upon continually and used in a final report to show internal awareness of the dataset.

**Acceptance Criteria:**
- [x] Make a list of teams that are using our data
- [x] Make a list of teams that were aware of our data when asked in interviews
- [x] Make a list of teams that were unaware of our data when asked in interviews
- [x] Represent these relationships in a visual diagram in Miro

Notes:
- An onion graph can be effectively used, with rings labelled 'Using', 'Aware', and 'Unaware'

**Comment by LindsayMacfarlane** [comment]
How does this differ from #85?

**Comment by jaimiebutton** [comment]
Hey Lindsay, does the recently created description answer your question?
