### ISSUE TITLE
Brainstorm Academia Contacts

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#87]
#### Description ####
As part of the public reporting project, reach out to identified key academic stakeholders at to better understand their use and need for industrial greenhouse gas emissions data. 

#### Checklist ####
- [x] Create a space in Miro
- [x] Brainstorm educational institutions to reach out to
- [x] Move institutions to Contact Tracker
- [x] Identify key contact(s) for each institution
- [x] Pass to project team for feedback

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
