### ISSUE TITLE
Hypothesis BC Gov users problem statement

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#88]
After a thorough discovery phase with BC Gov participants, we have leaned many challenges and opportunities from our colleagues. The creation of a hypothesis Problem Statement will help us summarize in our findings in a way that easily be shared, iterated on, and most of all... gives us a problem to work towards in future work.

Acceptance criteria:
- [x] Create frame in Miro about problem statements
- [x] Create hypothesis problem statements from research findings
- [x] Share problem statements with project team

**Comment by LindsayMacfarlane** [comment]
Thanks for this @jaimiebutton ! I the team has started to leave comments for consideration. It would be great if this could be shared on the Public Reporting (private) channel for input from CF and ES.
