### ISSUE TITLE
Research existing data visualization solutions

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#92]
Data visualization is a possible route we can follow to make our emissions data more accessible. But - why start from scratch? Let's see what existing solutions are out there (and maybe even learn from them!)

The scope of this ticket will be to find examples of existing _emissions data_ visualizations. Though we can no doubt learn from tools that display complex data of all kind, we'll keep it to this limited scope as a result of team capacity.

**Acceptance Criteria:**
- [x] Research existing digital/interactive emissions data visualizations in Canada
- [x] Research existing digital/interactive emissions data visualizations worldwide
- [x] Compile findings in Miro

**Comment by LindsayMacfarlane** [comment]
Looks good to me @jaimiebutton. To clarify, you want to look at existing tools/systems that display emissions data. Not specific platforms that can be used (e.g, Mapbox, ArcGIS, etc). As part of this and in the miro documentation, it would be good to indicate that you aren't comparing datasets, so our solution would probably differ.

**Comment by jaimiebutton** [comment]
Thanks for that clarification @LindsayMacfarlane - I've modified above. Good call about comparing datasets, though it could still be a recommendation of the project to compare/combine our data with another dataset to be able to tell a wider story. (So perhaps then best to keep it open until we narrow it down)

What are your thoughts?
