### ISSUE TITLE
Reach out to ESG reporting companies

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#95]
ESG reporting companies have a lot of insight they can share with us about how industry currently reports and how that will change in the near future. 

**Acceptance Criteria:**
- [x] Review list of potential companies below
- [x] Write outreach email
- [x] Send outreach email to identified ESG reporting companies

_Notes:_
The project team can reach out to the following companies:
PlanA (Europe)
Planetly (Europe)
Emitwise (Europe)
Watershed (US) 
Persefoni (US)
Novisto (https://novisto.com/solutions/by-industry/)
Doconomy (https://doconomy.com/)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
