### ISSUE TITLE
Reach out to Academia Contacts

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#96]
Following [ticket #87 ](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/87)of identifying academia contacts, this ticket captures outreach of academia.

**Acceptance Criteria:**
- [x] Draft outreach email
- [x] Send email to identified academia contacts

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
