### ISSUE TITLE
Identify industrial operators to contact

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#98]
Holding conversations with industrial operators is an important part of the Industry Phase of the project! This ticket captures the work of identify operators to reach out to.

**Acceptance Criteria:**
- [x] Reach out to Hanna for feedback
- [x] Give a heads up to CF + ES
- [x] Ask scrum team for list of CIIP primary contacts from this year's applications
- [x] Look through interview notes for recommended contacts
- [x] Add contacts to spreadsheet
- [x] Reach out to Geoff T for introductions
- [x] Generate list of potential industry operators to contact
- [x] Share list with project team for feedback

**Comment by LindsayMacfarlane** [comment]
I'm so excited for this phase @jaimiebutton. I anticipate we will get a lot of great feedback from this group.
