### ISSUE TITLE
Reach out to identified industrial operators

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#99]
Following [ticket #98](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-public-reporting/98) of identifying industrial operators, this ticket captures outreach of operators.

**Acceptance Criteria:**
- [x] Research cold call email best practices
- [x] Draft outreach email
- [x] Share with project team for feedback
- [x] Save email copy in project channel
- [x] Send email to identified operators

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton !
